const CONNECT_DIALOG = 'CONNECT_DIALOG';
const STAKE_LOADING = 'STAKE_LOADING';
const ACCOUNT_INFO = 'ACCOUNT_INFO';

const OPEN = 'OPEN_';
const CLOSE = 'CLOSE_';

export const OPEN_CONNECT_DIALOG = OPEN + CONNECT_DIALOG;
export const CLOSE_CONNECT_DIALOG = CLOSE + CONNECT_DIALOG;

export const OPEN_STAKE_LOADING = OPEN + STAKE_LOADING;
export const CLOSE_STAKE_LOADING = CLOSE + STAKE_LOADING;

export const OPEN_ACCOUNT_INFO = OPEN + ACCOUNT_INFO;
export const CLOSE_ACCOUNT_INFO = CLOSE + ACCOUNT_INFO;

export const UI_RESET = 'UI_RESET';
